title: "Kingsley's blog"
author: Kingsley
email: kingsleyemeka31@gmail.com
theme:  minima
description: > # this means to ignore newlines until "baseurl:"
  This is a tech blog where software engineers can learn awsome
  stuffs about software development.

# social links
twitter_username: emissary_b # DO NOT include the @ character, or else the build will fail!
github_username:  kingsley31 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
